package com.example.uicomposefigma.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF8b418f)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD6FA)
val md_theme_light_onPrimaryContainer = Color(0xFF36003C)
val md_theme_light_secondary = Color(0xFFA23F16)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCF)
val md_theme_light_onSecondaryContainer = Color(0xFF380D00)
val md_theme_light_tertiary = Color(0xFF006780)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB8EAFF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F28)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFC)
val md_theme_light_onBackground = Color(0xFF201A1B)
val md_theme_light_surface = Color(0xFFFCFCFC)
val md_theme_light_onSurface = Color(0xFF201A1B)
val md_theme_light_surfaceVariant = Color(0xFFEDDEE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4D444C)
val md_theme_light_outline = Color(0xFF7F747C)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEEF)
val md_theme_light_inverseSurface = Color(0xFF362F30)
val md_theme_light_inversePrimary = Color(0xFFa0cafd)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFd8dae0)
val md_theme_light_outlineVariant = Color(0xFFc3c7cf)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFA9FE)
val md_theme_dark_onPrimary = Color(0xFF560A5D)
val md_theme_dark_primaryContainer = Color(0xFF702776)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6FA)
val md_theme_dark_secondary = Color(0xFFFFB59B)
val md_theme_dark_onSecondary = Color(0xFF5B1A00)
val md_theme_dark_secondaryContainer = Color(0xFF812800)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCF)
val md_theme_dark_tertiary = Color(0xFF5DD5FC)
val md_theme_dark_onTertiary = Color(0xFF003544)
val md_theme_dark_tertiaryContainer = Color(0xFF004D61)
val md_theme_dark_onTertiaryContainer = Color(0xFFB8EAFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1B)
val md_theme_dark_onBackground = Color(0xFFECDFE0)
val md_theme_dark_surface = Color(0xFF201A1B)
val md_theme_dark_onSurface = Color(0xFFECDFE0)
val md_theme_dark_surfaceVariant = Color(0xFF4D444C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C3CC)
val md_theme_dark_outline = Color(0xFF998D96)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
val md_theme_dark_inverseSurface = Color(0xFFECDFE0)
val md_theme_dark_inversePrimary = Color(0xFF35618e)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF101418)
val md_theme_dark_outlineVariant = Color(0xFF42474e)
val md_theme_dark_scrim = Color(0xFF000000)